function [d_eta, d_etaprime] = eta0k_rhs(eta_hat, etaprime_hat, t, p)

    
    d_eta=etaprime_hat;
    d_etaprime =  4 * p.nu0 .* p.K2_deriv.*etaprime_hat  ... 
        -4*p.nu0^2.*p.K2_deriv.*p.K2_deriv.*eta_hat ...
    -p.d0*p.Bo* p.K2_deriv.*p.K2_deriv.*eta_hat ...
    + p.d0*p.g(t)*p.K2_deriv.*eta_hat;
end